Bloyal 221209
aws-samples/aws-healthcare-lifescience-ai-ml-sample-notebooks pull request #56
Opened 2022-12-14 19:53 UTC by brianloyal

*Description of changes:*
Copy editing and review of HIV and tabular breast cancer workshops.

Made the following updates:
## HIV workshop
- Reduced the number of training instances to 1 to stay below default quota.
- Reduced the number of training epochs to 20 to finish faster (validation results are still pretty good)
- Swapped out the `cat!` command to a `%pycat` to get syntax formatting of training script
- Copy editing

## Brest Cancer workshop
- Added the new sagemaker_datawrangler library to make pandas viewing pretty
- Copy editing

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2022-12-14 22:20 UTC, shamika requested changes
Added few comments

2022-12-15 14:43 UTC, brianloyal commented on workshops/Molecular-property-prediction/hiv-inhibitor-prediction-dgl/molecule-hiv-inhibitor-prediction-sagemaker.ipynb
>      "    instance_type=\"ml.p3.2xlarge\",\n",
Yeah, it seems to work fine on a single p3.2x. I was surprised that g4dns aren't available for training jobs by default

2022-12-15 14:43 UTC, brianloyal commented on workshops/Bring_Your_Own_Sklearn_Classifier/byo_mlp_classifier/sklearn_bring_your_own_MLP_Classifier_Breast_Diagnostic.ipynb
> +    "%pip install -U sagemaker>=2.48.0"
I'm cool with that - I'll update mine as well

2022-12-15 19:45 UTC, brianloyal commented
Shamika reviewed and approved

2022-12-15 19:45 UTC, merged